language: go
go_import_path: github.com/pkg/sftp
go:
  - 1.4.3
  - 1.5.4
  - 1.6.2
  - 1.7.1
  - tip

os:
  - linux
  - osx

sudo: false
  - tip

sudo: false

addons:
  ssh_known_hosts:
      - bitbucket.org

install:
  - go get -t -v ./...
  - ssh-keygen -t rsa -q -P "" -f /home/travis/.ssh/id_rsa

script:
  - go test -integration -v ./...
  - go test -testserver -v ./...
  - go test -integration -testserver -v ./...
  - go test -race -integration -v ./...
  - go test -race -testserver -v ./...
  - go test -race -integration -testserver -v ./...
